### ISSUE TITLE
macOS build failures with latest package

### ISSUE THREAD

**Issue by pkgw** [conda-forge/rust-feedstock#73]
It looks like the latest Rust compiler packages have an issue on macOS.

- [Compile failure on Tectonic 0.4.1](https://github.com/conda-forge/tectonic-feedstock/pull/39)
- [Failure on a test PR I submitted to librsvg](https://github.com/conda-forge/librsvg-feedstock/pull/64)

In both cases, it's the same linker error with libstd:

```
error: linking with `x86_64-apple-darwin13.4.0-clang` failed: exit code: 1
  |
  = note: "x86_64-apple-darwin13.4.0-clang" "-m64" "-arch" "x86_64" [... long command line ...]
  = note: Undefined symbols for architecture x86_64:
            "_linkat", referenced from:
                std::sys::unix::fs::link::had1f447ad1437b53 in libstd-518979da66993550.rlib(std-518979da66993550.std.byn0lf9c-cgu.0.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by isuruf** [comment]
I think rust bumped its minimum deployment target.

**Comment by isuruf** [comment]
I think this was unintended. It was introduced in https://github.com/rust-lang/rust/commit/ce00b3e2e0c5c0c88fe59fb45a1c25a8ff9e1836. Can you open an issue in Rust saying that linkat is only available in 10.10+?

cc @bollwyvl

**Comment by isuruf** [comment]
Can you send a PR to mark the 1.49 version on macos x86_64 as broken?

**Comment by pkgw** [comment]
Confirmed that Tectonic was able to build after ditching 1.49, so I think this problem is worked around for now, and there is conversation happening in rust-lang/rust#80804. Any opinions about whether this issue should stay open or be closed?

**Comment by pkgw** [comment]
rust-lang/rust#80804 has just been closed in rust-lang/rust#85953, so the next Rust release should hopefully work on our macOS again.

**Comment by pkgw** [comment]
The Rust folks report that this fix will make it into Rust 1.55 (but *not* the next stable release, which will be 1.54).

**Comment by hadim** [comment]
As a FYI, this is probably what prevent this osx-64 CI to pass: https://github.com/conda-forge/tokenizers-feedstock/pull/26#issuecomment-905428610

**Comment by isuruf** [comment]
1.55 is released now

**Comment by hadim** [comment]
Thanks. All the previously osx failing builds are now passing at https://github.com/conda-forge/tokenizers-feedstock/pull/26
